### ISSUE TITLE
Feature Request: Tag Blacklist for mechanical daisy

### ISSUE THREAD

**Issue by Saereth** [TheDrOfDoctoring/mechanicalbotania#1]
I noticed you cant insert living wood for example, into the mechanical daisy, this prevents a conversion loop from happening. There is another mod called Botanical Additions that adds an elven wood to dreamwood conversion but since dreamwood isnt blacklisted it will continue on converting to normal living wood after. Would it be possible to get a tag blacklist so we can tag conversions like this to stop them from happening? Would be very useful.

**Comment by TheDrOfDoctoring** [comment]
Hi, unless I misunderstand what you're asking, this mod only adds the Manamotor and Spinerette, not a mechanical daisy. You're probably looking for the "Botanical Machinery" mod.

**Comment by Saereth** [comment]
lol you're right I got mixed up, my apologies :)
